# Generated by Django 5.2.4 on 2025-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_charge', models.IntegerField()),
                ('transit_from', models.CharField(max_length=255)),
                ('transit_to', models.CharField(max_length=255)),
                ('consignor', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('packages', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('eway_bill', models.CharField(max_length=100)),
                ('consignment_invoice', models.CharField(max_length=100)),
                ('actual_weight', models.IntegerField()),
                ('charged_weight', models.IntegerField()),
                ('freight_charges', models.IntegerField(default=0)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('other_charges', models.IntegerField(default=0)),
                ('total_charge', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
            ],
        ),
    ]
