# Generated by Django 5.2.4 on 2025-07-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_status_orders_delivery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='value',
            new_name='consignment_value',
        ),
    ]
