# Generated by Django 5.2.4 on 2025-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_value_orders_consignment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='svds_bill_no',
            field=models.CharField(blank=True, editable=False, help_text='Auto‑generated 4‑char alphanumeric bill number', max_length=4, unique=True),
        ),
    ]
